# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181022_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsassigned',
            name='orig_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
