# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobsassigned_orig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='assigned',
            field=models.CharField(default='yes', max_length=50),
            preserve_default=False,
        ),
    ]
