# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='assigned',
            new_name='not_assigned',
        ),
    ]
