# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20181022_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='not_assigned',
            new_name='assigned',
        ),
    ]
